; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Wed Jul 01 2020 09:52:29 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

