; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sun Apr 01 2018 06:51:06 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P1