; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Mon May 22 2017 22:56:20 GMT-0400 (Eastern Daylight Time)

; Wait for set temperatures to be reached
M116 P0
