; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Jan 04 2019 20:46:37 GMT-0500 (Eastern Standard Time)

