all:
	echo "make install-all to install all machines"

install-all:
	echo "*** ENDER 5 ***" && cd ender-5 && make install
	echo "*** IDEX    ***" && cd idex    && make install
	echo "*** TAZ-6   ***" && cd taz6    && make install
	echo "*** VEHO    ***" && cd veho    && make install
	echo "*** V-KING  ***" && cd v-king  && make install
