; run-once.g
; called after config.g. When it has been executed, it is automatically deleted!
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Wed Jul 01 2020 09:52:28 GMT-0400 (Eastern Daylight Time)
M552 S0                    ; disable network
G4 P500                    ; wait half a second
M552 S1                    ; enable network
G4 P1000                   ; wait a second
M98 P"/sys/passwords.g"
M552 S1                    ; enable network

