; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Sun Dec 01 2019 12:21:57 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G30 P0 X5 Y140 Z-99999
G30 P1 X275 Y140 Z-99999 S2
