; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Sun Dec 01 2019 12:21:57 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G30 P0 X-10 Y285 Z-99999
G30 P1 X288 Y285 Z-99999
;G30 P2 X288 Y-9 Z-99999
G30 P2 X-10 Y-9 Z-99999 S2

G1 Y0 X0 Z5
G92 Z4.9

