; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Sun Dec 01 2019 12:21:58 GMT-0500 (Eastern Standard Time)
G91               ; relative positioning
G1 H2 Z5 F6000    ; lift Z relative to current position
G90
M98 P"/sys/homez-common.g"