; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Sun Dec 01 2019 12:22:00 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

