mapping = {
	"before_layer_gcode", {'key': 'before_layer_change_gcode', 'scalar': True, 'ed': 7},
	"default_filament_profile", {'key': 'default_filament_profile', 'scalar': False, 'ed': 0},
	"default_print_profile", {'key': 'default_print_profile', 'scalar': True, 'ed': 0},
	"deretract_speed", {'key': 'deretraction_speed', 'scalar': False, 'ed': 3},
	"end_gcode", {'key': 'machine_end_gcode', 'scalar': True, 'ed': 8},
	"extruder_clearance_radius", {'key': 'extruder_clearance_radius', 'scalar': True, 'ed': 0},
	"extruder_clearance_height", {'key': 'extruder_clearance_height_to_rod', 'scalar': True, 'ed': 7},
	"extruder_colour", {'key': 'extruder_colour', 'scalar': False, 'ed': 0},
	"extruder_offset", {'key': 'extruder_offset', 'scalar': False, 'ed': 0},
	"layer_gcode", {'key': 'layer_change_gcode', 'scalar': True, 'ed': 4},
	"machine_max_acceleration_e", {'key': 'machine_max_acceleration_e', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_extruding", {'key': 'machine_max_acceleration_extruding', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_retracting", {'key': 'machine_max_acceleration_retracting', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_travel", {'key': 'machine_max_acceleration_travel', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_x", {'key': 'machine_max_acceleration_x', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_y", {'key': 'machine_max_acceleration_y', 'scalar': False, 'ed': 0},
	"machine_max_acceleration_z", {'key': 'machine_max_acceleration_z', 'scalar': False, 'ed': 0},
	"machine_max_jerk_x", {'key': 'machine_max_jerk_x', 'scalar': False, 'ed': 0},
	"machine_max_jerk_y", {'key': 'machine_max_jerk_y', 'scalar': False, 'ed': 0},
	"machine_max_jerk_z", {'key': 'machine_max_jerk_z', 'scalar': False, 'ed': 0},
	"machine_min_extruding_rate", {'key': 'machine_min_extruding_rate', 'scalar': False, 'ed': 0},
	"machine_min_travel_rate", {'key': 'machine_min_travel_rate', 'scalar': False, 'ed': 0},
	"max_layer_height", {'key': 'max_layer_height', 'scalar': False, 'ed': 0},
	"min_layer_height", {'key': 'min_layer_height', 'scalar': False, 'ed': 0},
	"nozzle_diameter", {'key': 'nozzle_diameter', 'scalar': False, 'ed': 0},
	"bed_shape", {'key': 'printable_area', 'scalar': False, 'ed': 8},
	"printer_model", {'key': 'printer_model', 'scalar': True, 'ed': 0},
	"printer_settings_id", {'key': 'printer_settings_id', 'scalar': True, 'ed': 0},
	"printer_technology", {'key': 'printer_technology', 'scalar': True, 'ed': 0},
	"printer_variant", {'key': 'printer_variant', 'scalar': True, 'ed': 0},
	"retract_before_travel", {'key': 'retraction_minimum_travel', 'scalar': False, 'ed': 10},
	"retract_before_wipe", {'key': 'retract_before_wipe', 'scalar': False, 'ed': 0},
	"retract_layer_change", {'key': 'retract_when_changing_layer', 'scalar': False, 'ed': 12},
	"retract_length", {'key': 'retraction_length', 'scalar': False, 'ed': 3},
	"retract_length_toolchange", {'key': 'retract_length_toolchange', 'scalar': False, 'ed': 0},
	"retract_restart_extra", {'key': 'retract_restart_extra', 'scalar': False, 'ed': 0},
	"retract_restart_extra_toolchange", {'key': 'retract_restart_extra_toolchange', 'scalar': False, 'ed': 0},
	"retract_speed", {'key': 'retraction_speed', 'scalar': False, 'ed': 3},
	"silent_mode", {'key': 'silent_mode', 'scalar': True, 'ed': 0},
	"single_extruder_multi_material", {'key': 'single_extruder_multi_material', 'scalar': True, 'ed': 0},
	"start_gcode", {'key': 'machine_start_gcode', 'scalar': True, 'ed': 8},
	"wipe", {'key': 'wipe', 'scalar': False, 'ed': 0}
}

machine_mapping_fixed = {
    "from": "User",
    "is_custom_defined": "0",
    "scan_first_layer": "0",
    "nozzle_type": "hardened_steel",
	"inherits", {'key': 'instantiation', 'scalar': True, 'ed': 9},
	"machine_max_jerk_e", {'key': 'machine_pause_gcode', 'scalar': True, 'ed': 9},
}

# name -> printer_settings_id
