; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Sun Dec 01 2019 12:21:59 GMT-0500 (Eastern Standard Time)

M104 S0
M140 S0
M106 S0
G91
G1 Z2
G90
G1 X0 Y270 F9000
M84