; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Jan 04 2019 20:46:36 GMT-0500 (Eastern Standard Time)
G91              ; relative positioning
G1 Z2 F6000 S2   ; lift Z relative to current position
G90              ; absolute positioning
G1 X155 Y180 F12000 ; go to center
; G1 X0 Y360 F12000  ; go to a corner likely to be pristinely clean
G30              ; home Z by probing the bed
